// GLOBAL
export const url = process.env.REACT_APP_API;

// ADMINS

// APPLICATIONS

// CANDIDATES
export const GET_CANDIDATES_FETCHING = 'GET_CANDIDATES_FETCHING';
export const GET_CANDIDATES_FULLFILLED = 'GET_CANDIDATES_FULLFILLED';
export const GET_CANDIDATES_REJECTED = 'GET_CANDIDATES_REJECTED';

export const GET_CANDIDATE_BY_ID_FETCHING = 'GET_CANDIDATE_BY_ID_FETCHING';
export const GET_CANDIDATE_BY_ID_FULLFILLED = 'GET_CANDIDATE_BY_ID_FULLFILLED';
export const GET_CANDIDATE_BY_ID_REJECTED = 'GET_CANDIDATE_BY_ID_REJECTED';

export const CREATE_CANDIDATES_FETCHING = 'CREATE_CANDIDATES_FETCHING';
export const CREATE_CANDIDATES_FULLFILLED = 'CREATE_CANDIDATES_FULLFILLED';
export const CREATE_CANDIDATES_REJECTED = 'CREATE_CANDIDATES_REJECTED';

export const UPDATE_CANDIDATES_FETCHING = 'UPDATE_CANDIDATES_FETCHING';
export const UPDATE_CANDIDATES_FULLFILLED = 'UPDATE_CANDIDATES_FULLFILLED';
export const UPDATE_CANDIDATES_REJECTED = 'UPDATE_CANDIDATES_REJECTED';

export const DELETE_CANDIDATES_FETCHING = 'DELETE_CANDIDATES_FETCHING';
export const DELETE_CANDIDATES_FULLFILLED = 'DELETE_CANDIDATES_FULLFILLED';
export const DELETE_CANDIDATES_REJECTED = 'DELETE_CANDIDATES_REJECTED';

// COMPANIES

// INTERVIEWS

// POSITIONS

// PROFILES

// PSYCHOLOGISTS

// SESSIONS
