// GLOBAL
export const url = process.env.REACT_APP_API;

// ADMINS
export const GET_APPLICATION_FETCHING = 'GET_APPLICATION_FETCHING';
export const GET_APPLICATION_FULFILLED = 'GET_APPLICATION_FULFILLED';
export const GET_APPLICATION_REJECTED = 'GET_APPLICATION_REJECTED';

export const UPDATE_SELECTED_APPLICATION = 'UPDATE_SELECTED_APPLICATION';
export const APPLICATIONS_CLEANUP = 'APPLICATIONS_CLEANUP_CLEANUP';

export const GET_APPLICATIONS_FETCHING = 'GET_APPLICATIONS_FETCHING';
export const GET_APPLICATIONS_FULFILLED = 'GET_APPLICATIONS_FULFILLED';
export const GET_APPLICATIONS_REJECTED = 'GET_APPLICATIONS_REJECTED';

export const DELETE_APPLICATION_FETCHING = 'DELETE_APPLICATION_FETCHING';
export const DELETE_APPLICATION_FULFILLED = 'DELETE_APPLICATION_FULFILLED';
export const DELETE_APPLICATION_REJECTED = 'DELETE_APPLICATION_REJECTED';

export const CREATE_APPLICATION_FETCHING = 'CREATE_APPLICATION_FETCHING';
export const CREATE_APPLICATION_FULFILLED = 'CREATE_APPLICATION_FULFILLED';
export const CREATE_APPLICATION_REJECTED = 'CREATE_APPLICATION_REJECTED';

export const UPDATE_APPLICATION_FETCHING = 'UPDATE_APPLICATION_FETCHING';
export const UPDATE_APPLICATION_FULFILLED = 'UPDATE_APPLICATION_FULFILLED';
export const UPDATE_APPLICATION_REJECTED = 'UPDATE_APPLICATION_REJECTED';

export const GET_APPLICATIONS_OPTIONS_FETCHING = 'GET_APPLICATIONS_OPTIONS_FETCHING';
export const GET_APPLICATIONS_OPTIONS_FULFILLED = 'GET_APPLICATIONS_OPTIONS_FULFILLED';
export const GET_APPLICATIONS_OPTIONS_REJECTED = 'GET_APPLICATIONS_OPTIONS_REJECTED';

// APPLICATIONS

// CANDIDATES

// COMPANIES

// INTERVIEWS

// POSITIONS

// PROFILES

// PSYCHOLOGISTS

// SESSIONS

//MODAL
export const SHOW_MODAL = 'SHOW_MODAL';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
