//CANDIDATE SESSIONS
export const GET_AVAILABLE_DATES_FETCHING = 'GET_AVAILABLE_DATES_FETCHING';
export const GET_AVAILABLE_DATES_FULFILLED = 'GET_AVAILABLE_DATES_FULFILLED';
export const GET_AVAILABLE_DATES_REJECTED = 'GET_AVAILABLE_DATES_REJECTED';

export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION';

export const CREATE_SESSION_FETCHING = 'CREATE_SESSION_FETCHING';
export const CREATE_SESSION_FULFILLED = 'CREATE_SESSION_FULFILLED';
export const CREATE_SESSION_REJECTED = 'CREATE_SESSION_REJECTED';

export const UPDATE_SESSION_FETCHING = 'UPDATE_SESSION_FETCHING';
export const UPDATE_SESSION_FULFILLED = 'UPDATE_SESSION_FULFILLED';
export const UPDATE_SESSION_REJECTED = 'UPDATE_SESSION_REJECTED';

export const DELETE_SESSION_FETCHING = 'DELETE_SESSION_FETCHING';
export const DELETE_SESSION_FULFILLED = 'DELETE_SESSION_FULFILLED';
export const DELETE_SESSION_REJECTED = 'DELETE_SESSION_REJECTED';

export const GET_SESSION_FETCHING = 'GET_SESSION_FETCHING';
export const GET_SESSION_FULFILLED = 'GET_SESSION_FULFILLED';
export const GET_SESSION_REJECTED = 'GET_SESSION_REJECTED';
