//CANDIDATE SESSIONS
export const GET_AVAILABLE_DATES_FETCHING = 'GET_AVAILABLE_DATES_FETCHING';
export const GET_AVAILABLE_DATES_FULFILLED = 'GET_AVAILABLE_DATES_FULFILLED';
export const GET_AVAILABLE_DATES_REJECTED = 'GET_AVAILABLE_DATES_REJECTED';

export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION';

export const CREATE_SESSION_FETCHING = 'CREATE_SESSION_FETCHING';
export const CREATE_SESSION_FULFILLED = 'CREATE_SESSION_FULFILLED';
export const CREATE_SESSION_REJECTED = 'CREATE_SESSION_REJECTED';
