//CANDIDATE SESSIONS
export const GET_AVAILABLE_DATES_FETCHING = 'GET_AVAILABLE_DATES_FETCHING';
export const GET_AVAILABLE_DATES_FULFILLED = 'GET_AVAILABLE_DATES_FULFILLED';
export const GET_AVAILABLE_DATES_REJECTED = 'GET_AVAILABLE_DATES_REJECTED';
